[package]
name = "signifide"
version = "0.1.0"
edition = "2021"
description = "Signing at the edge"
license = "Apache-2.0"
keywords = ["cesr", "keri", "acdc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
